title: "MobileSpeech: A Fast and High-Filelity Framework for Mobile Zero-Shot Text-to-Speech"
# description: Xulong Zhang

theme: jekyll-theme-cayman

github:
  repository_url: https://github.com/MobileSpeech/
